--INSERT INTO secoes VALUES (null, "AIPSIN2020"), (null, "Recursos Humanos"), (null, "Comercial WEG");
--INSERT INTO gestores VALUES (67264, "123", 1, "Brayan Vinicius Jordan", "brayan.11fera@gmail.com");
--INSERT INTO gestores VALUES (67265, "1234", 3, "Brendon Gabriel Ribeiro da Silva", "brendon.11fera@gmail.com");
