--INSERT INTO ccpagantes VALUES (null, 1, 1, 100);
--INSERT INTO ccpagantes VALUES (null, 2, 2, 100);
--INSERT INTO ccpagantes VALUES (null, 3, 3, 100);
--INSERT INTO ccpagantes VALUES (null, 4, 4, 100);
--INSERT INTO ccpagantes VALUES (null, 5, 5, 50);
--INSERT INTO ccpagantes VALUES (null, 5, 5, 50);